# Install script for directory: E:/voy/102/third/opencv/opencv-4.8.0

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/install")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Release")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "FALSE")
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xlicensesx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/etc/licenses" TYPE FILE RENAME "flatbuffers-LICENSE.txt" FILES "E:/voy/102/third/opencv/opencv-4.8.0/3rdparty/flatbuffers/LICENSE.txt")
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xlicensesx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/etc/licenses" TYPE FILE RENAME "opencl-headers-LICENSE.txt" FILES "E:/voy/102/third/opencv/opencv-4.8.0/3rdparty/include/opencl/LICENSE.txt")
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xdevx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/opencv2" TYPE FILE FILES "E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/cvconfig.h")
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xdevx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/opencv2" TYPE FILE FILES "E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/opencv2/opencv_modules.hpp")
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xdevx" OR NOT CMAKE_INSTALL_COMPONENT)
  if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/x64/vc16/staticlib/OpenCVModules.cmake")
    file(DIFFERENT EXPORT_FILE_CHANGED FILES
         "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/x64/vc16/staticlib/OpenCVModules.cmake"
         "E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/CMakeFiles/Export/x64/vc16/staticlib/OpenCVModules.cmake")
    if(EXPORT_FILE_CHANGED)
      file(GLOB OLD_CONFIG_FILES "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/x64/vc16/staticlib/OpenCVModules-*.cmake")
      if(OLD_CONFIG_FILES)
        message(STATUS "Old export file \"$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/x64/vc16/staticlib/OpenCVModules.cmake\" will be replaced.  Removing files [${OLD_CONFIG_FILES}].")
        file(REMOVE ${OLD_CONFIG_FILES})
      endif()
    endif()
  endif()
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/x64/vc16/staticlib" TYPE FILE FILES "E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/CMakeFiles/Export/x64/vc16/staticlib/OpenCVModules.cmake")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/x64/vc16/staticlib" TYPE FILE FILES "E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/CMakeFiles/Export/x64/vc16/staticlib/OpenCVModules-debug.cmake")
  endif()
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/x64/vc16/staticlib" TYPE FILE FILES "E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/CMakeFiles/Export/x64/vc16/staticlib/OpenCVModules-release.cmake")
  endif()
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xdevx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/x64/vc16/staticlib" TYPE FILE FILES
    "E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/win-install/OpenCVConfig-version.cmake"
    "E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/win-install/x64/vc16/staticlib/OpenCVConfig.cmake"
    )
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xdevx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/." TYPE FILE FILES
    "E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/win-install/OpenCVConfig-version.cmake"
    "E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/win-install/OpenCVConfig.cmake"
    )
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xlibsx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/." TYPE FILE PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ FILES "E:/voy/102/third/opencv/opencv-4.8.0/LICENSE")
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xscriptsx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/." TYPE FILE PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE FILES "E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/CMakeFiles/install/setup_vars_opencv4.cmd")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/3rdparty/zlib/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/3rdparty/libjpeg-turbo/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/3rdparty/libtiff/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/3rdparty/libwebp/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/3rdparty/openjpeg/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/3rdparty/libpng/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/3rdparty/protobuf/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/3rdparty/quirc/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/include/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/calib3d/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/core/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/dnn/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/features2d/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/flann/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/gapi/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/highgui/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/imgcodecs/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/imgproc/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/java/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/js/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/ml/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/objc/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/objdetect/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/photo/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/python/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/stitching/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/ts/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/video/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/videoio/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/world/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/alphamat/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/aruco/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/bgsegm/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/bioinspired/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/ccalib/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/cnn_3dobj/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/cudaarithm/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/cudabgsegm/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/cudacodec/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/cudafeatures2d/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/cudafilters/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/cudaimgproc/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/cudalegacy/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/cudaobjdetect/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/cudaoptflow/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/cudastereo/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/cudawarping/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/cudev/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/cvv/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/datasets/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/dnn_objdetect/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/dnn_superres/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/dpm/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/face/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/freetype/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/fuzzy/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/hdf/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/hfs/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/img_hash/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/intensity_transform/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/julia/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/line_descriptor/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/matlab/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/mcc/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/optflow/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/ovis/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/phase_unwrapping/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/plot/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/quality/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/rapid/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/reg/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/rgbd/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/saliency/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/sfm/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/shape/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/stereo/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/structured_light/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/superres/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/surface_matching/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/text/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/tracking/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/videostab/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/viz/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/wechat_qrcode/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/xfeatures2d/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/ximgproc/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/xobjdetect/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/.firstpass/xphoto/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/core/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/flann/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/imgproc/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/intensity_transform/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/ml/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/phase_unwrapping/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/photo/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/plot/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/quality/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/reg/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/surface_matching/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/xphoto/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/features2d/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/fuzzy/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/hfs/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/img_hash/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/imgcodecs/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/line_descriptor/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/saliency/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/calib3d/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/datasets/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/highgui/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/objdetect/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/rapid/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/rgbd/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/shape/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/stitching/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/structured_light/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/xobjdetect/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/aruco/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/bioinspired/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/ccalib/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/dpm/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/face/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/modules/objc_bindings_generator/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/doc/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/data/cmake_install.cmake")
  include("E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/apps/cmake_install.cmake")

endif()

if(CMAKE_INSTALL_COMPONENT)
  set(CMAKE_INSTALL_MANIFEST "install_manifest_${CMAKE_INSTALL_COMPONENT}.txt")
else()
  set(CMAKE_INSTALL_MANIFEST "install_manifest.txt")
endif()

string(REPLACE ";" "\n" CMAKE_INSTALL_MANIFEST_CONTENT
       "${CMAKE_INSTALL_MANIFEST_FILES}")
file(WRITE "E:/voy/102/third/opencv/opencv-4.8.0_build_vs2019_x64/${CMAKE_INSTALL_MANIFEST}"
     "${CMAKE_INSTALL_MANIFEST_CONTENT}")
